// USER
export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const AUTH = "AUTH"
export const LOGOUT = "LOGOUT"

// PRODUCTS
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_PRODUCT_INFO = "GET_PRODUCT_INFO"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const SHOW_MORE_PRODUCTS = "SHOW_MORE_PRODUCTS"
export const SET_CONTINENT_FILTER = "SET_CONTINENT_FILTER"
export const SET_PRICE_FILTER = "SET_PRICE_FILTER"